### ISSUE TITLE
Silent install via management (Local System) does not register it as an system-wide (uninstallable) application in Windows and creates no start menu entry

### ISSUE THREAD

**Issue by Lukas-UAUX** [kaixxx/noScribe#100]
Hi, 

it seems that there is a tiny bug in your Windows installer configuration when a silent install via '`/S`' is performed and run as 'Local System' user - which is common for software management / deployment systems. So far it installs all Files to '`C:\Program Files (x86)\noScribe`' (is it really an 32bit application?) but afterwards the application is not registered correctly as a system-wide application to 

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`

or for 32bit Software on 64bit Systems:

`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall`

That means it will not be listed in the Windows settings for uninstalling and most inventory systems will not find it (by default). 

Also no (system wide) start menu in '`C:\ProgramData\Microsoft\Windows\Start Menu\Programs`' entry is created.

Looking through the registry it seems that the installer only does the registry and icons for the user running the installer even when a system wide installation is performed. This is a common issue for a lot of applications that they do register themselves only in the context of the user running the installer (HKEY_CURRENT_USER), and for a user driven install that can be kinda enough, but for a deployment scenario this breaks by registering it only to the '`LocalSystem`' user (or any other user system administrator). 

For now i can fix it for us by running a script afterwards moving the registry entry and the icon to the correct location but it would be cool if it could be fixed 'upstream' as this software looks very promising to replace some expensive closed source applications at our university.

**Comment by kaixxx** [comment]
Thank you for bringing this up, and sorry that it took so long for me to respond. I was working on other projects. However, I've now directed my attention back to noScribe and are slowly moving towards a next release. 
So, I looked into this issue and modified my installer script so that it will always install noScribe system-wide. 
Also, an installer run with the `/S` command will now silently uninstall all previous versions found, no matter if they are installed system-wide or for the current user. Do you think this is a viable solution?

**Comment by kaixxx** [comment]
> start menu entries are still created in the users AppData instead of the %ALLUSERSPROFILE%

Ah, I missed that. I will create a new issue to remember changing this in the next release. Thanks!
