### ISSUE TITLE
Mac M2 - CPU Heat

### ISSUE THREAD

**Issue by core-hn** [kaixxx/noScribe#99]
Hi everyone,

First, I have to thank the developpers, this app looks really great !
3 times I try to launch a transcription.
I don't experience issues I read, my computer looks to start successfully the transcription, segmenting step OK, identifying speakers too. But, since the start, my CPU heats really hard. It gets up to 100°C, so I have to stop and let my computer cool down.

Tried : 
- 0.5.0b and not-b versions of arm64 dmg → nothing different
- `pyannote_xpu` to `cpu`, same with `whisper_xpu` → same heat issue, but longer

This time I only have 2 hours interview to transcript, so I trust my device to handle this temperature. But later I'll have many hours to transcript. What would you advise me to do ? Should I wait a fix, or try on another device (I have a rpi on debian, but arm too).

Thanks for help and advices,
Have a nice day :)

**Comment by gernophil** [comment]
hey @core-hn,

could you give us a little more detailed specs on your Mac:
- Is it a MacBook or a stationary Mac (and which one)?
- What CPU exactly?
  - M2, M2 Pro, M2 Max?
  - How many cores (easiest would be to share a screenshot of the "About this Mac" windows (but please remove the serial before sharing or simply type the info here by hand :))?
  - how much memory
  - What macOS version?
This sounds more like a cooling issue. Maybe too much dust in the cooling system or a OS controlling issue.

**Comment by core-hn** [comment]
Thanks @gernophil !

It's a Macbook Air M2, 8Go on Sequoia 15.1 (8 cores, 4 perf 4 efficiency)

No dust, but maybe an update would solve? I'm gonna try, and come back here to feedback.
Mostly I noticed people don't monitor the temperature, so maybe that's a normal case.

**Comment by gernophil** [comment]
If it's an Air M2 then dust wouldn't a problem, even if it was there, because it doesn't have any fan :). Sequioa 15.1 is also the most recent macOS, so there is no update possible. I googled a little and 100°C seem to be quite "normal" for Macbook Airs. Just google "macbook air 100 degrees" and you get a lot of hits. One statement that gave me at least a little relief was this: "This allowed the chip to settle in at around 100 degrees, which is still hot but is still considered safe by the industry."(https://www.tomshardware.com/laptops/macbooks/m3-macbook-air-hits-eye-popping-114-degrees-celsius-in-stress-test-and-didnt-melt)

So, I really think this is hot, but it seems to be normal and "safe". You might run into issues with only 8GB of RAM though. Might be to little for noScribe and could lead to the MPS backend out of memory error.

I would strongly advice using `mps` for both `pyannote_xpu` and `whisper_xpu` since this will lead to less CPU load.

**Comment by core-hn** [comment]
Oh @gernophil , thanks ! I think my  monitoring software isn't aware of this.

Sorry for the disturbing, and again thanks.

I'll try my complete transcription and come here to feedback and close this topic.

Have a nice day 😄

**Comment by gernophil** [comment]
No worries :). I would have also wondered (and am still wondering) about this high temp :). Love to hear back, if 8GB is actually enough now :).
